// utils/extractImagePrompts.jsx

/**
 * This function extracts image prompts from the generated story.
 * It assumes the story is divided into sections identified by "Sección 1", "Sección 2", etc.
 * Each section should contain a description of the scene, which will be used as a prompt for generating images.
 *
 * @param {string} generatedStory - The story generated by ChatGPT.
 * @returns {string[]} - An array of prompts for generating images.
 */
const extractImagePrompts = (generatedStory) => {
    const sections = generatedStory.split(/Sección \d+/);
    const prompts = sections.map(section => {
      const match = section.match(/([^:]+):(.+)/);
      if (match) {
        const [, title, description] = match;
        return `${title.trim()}: ${description.trim()}`;
      }
      return null;
    }).filter(prompt => prompt);
  
    return prompts;
  };
  
  export default extractImagePrompts;
  